# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

# Version of formatting rules
version = "Two"

# Maximum line width
max_width = 100

# Use Unix line endings
newline_style = "Unix"

# Use spaces for indentation
hard_tabs = false
tab_spaces = 4

# Brace style
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"

# Function arguments
fn_args_layout = "Tall"
fn_single_line = false

# Imports
imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"

# Reorder imports and module declarations
reorder_imports = true
reorder_modules = true

# Use field initialize shorthand
use_field_init_shorthand = true

# Format strings
format_strings = true

# Comments
normalize_comments = true
wrap_comments = true
comment_width = 80

# Match statements
match_block_trailing_comma = true

# Chains
chain_width = 60
single_line_if_else_max_width = 50

# Spaces
spaces_around_ranges = false

# Misc
trailing_comma = "Vertical"
blank_lines_upper_bound = 2
edition = "2021"