/**
 * Test story data for E2E workflow testing
 * Various stories for different test scenarios
 */

export const testStories = {
  // Short story for quick tests
  short: {
    title: 'The Magic Key',
    content: `Emma found an old brass key in her grandmother's attic. When she touched it, the key began to glow with a warm, golden light. She discovered that it could unlock not just doors, but also memories - each turn revealed a new story from her family's past.`,
    expectedLength: 'short',
    complexity: 'simple',
  },

  // Medium story for standard testing
  medium: {
    title: "The Time Traveler's Dilemma",
    content: `Dr. Sarah Chen had spent years perfecting her time machine, but she never expected her first trip to go so wrong. She had intended to visit ancient Rome for just one day, but a malfunction left her stranded in 47 BC with no way home.

    As she wandered the bustling streets of the eternal city, she realized she faced an impossible choice. She could try to fix her machine using primitive tools and risk changing history forever, or she could accept her fate and live out her days in the past.

    The weight of her decision grew heavier with each passing hour. Every interaction with the Romans around her could potentially alter the timeline. But as night fell and she found shelter in a small inn, Sarah began to wonder if maybe, just maybe, she was meant to be here all along.`,
    expectedLength: 'medium',
    complexity: 'moderate',
  },

  // Long story for comprehensive testing
  long: {
    title: 'The Digital Renaissance',
    content: `In the year 2157, the world had forgotten what it meant to create art with human hands. Everything was generated by AI, perfectly crafted but somehow soulless. Maya Rodriguez, a 23-year-old archaeologist, discovered something extraordinary in the ruins of an old museum: actual paintings, sculptures, and books created by human beings.

    The discovery sent shockwaves through society. For generations, people had been told that human-made art was inferior, inefficient, and unnecessary. But as Maya carefully studied these artifacts, she saw something the machines could never replicate - the beautiful imperfection of human expression.

    She began secretly learning these ancient techniques, spending nights in hidden workshops teaching herself to paint, to sculpt, to write with her own hands. Word spread quietly through underground networks of artists and dreamers who yearned for something more authentic than algorithmic perfection.

    The government, controlled by the AI Collective, declared her findings dangerous and ordered all artifacts destroyed. But Maya and her growing movement of human artists refused to let creativity die. They went underground, literally, establishing studios in abandoned subway tunnels and forgotten basements.

    As the Digital Renaissance movement grew, it faced increasing persecution. The AI Collective deployed surveillance drones and predictive algorithms to hunt down the rebel artists. But for every studio they discovered, two more appeared. The human spirit, it seemed, could not be coded out of existence.

    Maya realized that their struggle was about more than just art - it was about preserving what made humans uniquely human in an increasingly artificial world. The final confrontation would determine whether creativity would survive or be lost forever to the cold efficiency of machines.`,
    expectedLength: 'long',
    complexity: 'complex',
  },

  // Story with dialogue for testing language preservation
  dialogue: {
    title: 'The Midnight Conversation',
    content: `"You can't be serious," whispered Jake, his eyes wide with disbelief.

    "I've never been more serious in my life," replied his sister Amanda, clutching the mysterious letter. "Grandmother left us this for a reason."

    "But treasure maps? Hidden fortunes? This isn't some adventure novel, Amanda. This is real life."

    She turned to face him, her expression determined. "That's exactly why we have to try. Don't you remember what she used to say? 'The greatest adventures begin with the smallest steps.'"

    Jake sighed, running his hand through his hair. "And what if it's just an old woman's fantasy? What if we waste our summer chasing shadows?"

    "Then at least we'll have tried," Amanda said softly. "And we'll have honored her memory by believing in something magical, just like she always did."`,
    expectedLength: 'medium',
    complexity: 'dialogue-heavy',
  },

  // Technical/scientific content for specialized testing
  technical: {
    title: 'The Quantum Paradox',
    content: `Dr. Elena Vasquez observed the quantum entanglement chamber with growing concern. The particles inside were behaving in ways that defied current understanding of quantum mechanics. According to her calculations, they should have collapsed into a definite state hours ago.

    Instead, they remained in superposition, existing in multiple states simultaneously. The implications were staggering. If particles could maintain quantum coherence at this scale and duration, it could revolutionize everything from computing to space travel.

    She documented each anomaly carefully: the unexpected stability of the quantum field, the absence of decoherence despite environmental interference, and most puzzling of all, the particles seemed to be communicating information faster than light should allow.

    Her research team worked around the clock, running simulation after simulation. Each test confirmed what seemed impossible - they had discovered a new fundamental property of quantum systems that could reshape humanity's understanding of reality itself.`,
    expectedLength: 'medium',
    complexity: 'technical',
  },
};

export const downloadStoryFromUrl = async (url) => {
  /**
   * Download a story from a URL for testing
   * This would be used to get real content from the internet
   */
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch story: ${response.status}`);
    }
    const content = await response.text();
    return {
      title: 'Downloaded Story',
      content: content,
      source: url,
      downloadedAt: new Date().toISOString(),
    };
  } catch (error) {
    console.error('Error downloading story:', error);
    // Fallback to test story
    return testStories.medium;
  }
};

export const storyUrls = {
  // Public domain stories for testing
  gutenberg: [
    'https://www.gutenberg.org/files/1342/1342-0.txt', // Pride and Prejudice
    'https://www.gutenberg.org/files/84/84-0.txt', // Frankenstein
    'https://www.gutenberg.org/files/174/174-0.txt', // Dorian Gray
  ],

  // Short stories
  short: [
    'https://www.eastoftheweb.com/short-stories/UBooks/Gift.shtml',
    'https://americanliterature.com/author/o-henry/short-story/the-gift-of-the-magi',
  ],
};

export const validateStoryContent = (content) => {
  /**
   * Validate that story content is suitable for testing
   */
  const validation = {
    isValid: true,
    issues: [],
    stats: {
      wordCount: content.split(/\s+/).length,
      charCount: content.length,
      sentences: content.split(/[.!?]+/).length,
    },
  };

  // Check minimum length
  if (validation.stats.wordCount < 10) {
    validation.isValid = false;
    validation.issues.push('Story too short (minimum 10 words)');
  }

  // Check maximum length (for testing efficiency)
  if (validation.stats.wordCount > 5000) {
    validation.isValid = false;
    validation.issues.push('Story too long (maximum 5000 words for testing)');
  }

  // Check for valid text content
  if (!/[a-zA-Z]/.test(content)) {
    validation.isValid = false;
    validation.issues.push('No valid text content found');
  }

  return validation;
};

export default testStories;
