name: Code Quality & Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run Prettier Check
      run: npm run format:check
    
    - name: Security Audit
      run: npm audit --audit-level=moderate
    
    - name: Run Security Linting
      run: npx eslint 'js/**/*.js' --no-eslintrc -c .eslintrc.security.js
    
    - name: Generate Code Quality Report
      run: |
        npm run quality
        echo "Code quality report generated in reports/plato"
    
    - name: Upload Quality Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-reports
        path: reports/
    
    - name: Comment PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Code quality checks passed! Check artifacts for detailed reports.'
          })